FORMAT: 1A
HOST: http://localhost:8080

# TrueBlocks API

**TrueBlocks** provides easy access to Ethereum **blocks**, **transactions**, **receipts**, **logs**, **trace data**, **abis**, and **prices** directly from your own Ethereum node. An Ethereum RPC endpoint, which may be either remote or local (preferred), is required.

**TrueBlocks** is different from other solutions, however, in two ways: (1) the primary focus of **TrueBlocks** is delivering complete, fully-detailed, audit-quality historical lists of transactions for individual or groups of Ethereum addresses; and (2) **TrueBlocks** is decentralized from first principals.

Any data available from the node is delivered to you directly, without the intervention of a third party. Other data, such as prices and abi definitions, is provided from immutable data stores with an optional mechanism to participate in community-wide sharing of that data.

#### Installation

Instructions for installing the package are here.

#### Design Documents

Discussion of design choices is here.

#### Example Usage

Examples of using the API are here.

# Group Accounts

## List [<<GENERATE:URI:list>>]

A resource that tells trueBlocks that you want to list appearances for `address`. Trueblocks returns its appearance index, each appearance consisting of `{blockNumber, txId}`. 

+ Parameters

<<GENERATE:PARAMS:list>>

### /list [GET]

+ Request Plain Text Export

    + Headers
    
            Accept: text/plain
            
+ Response 200 (text/plain)
    
    + Body
    
            89796   6
            89880   3
            94675   17
            94754   3
            99979   10
            101279  0
            105338  18
            105439  2
            110350  40
            110457  1
            112698  35
            112789  0

## Export [<<GENERATE:URI:export>>]

A resource that tells trueblocks that you want to export transactions for `address`. Trueblocks will use its appearance index to ask the node for detailed information about each appearance. The information is then returned in either JSON or CSV.

+ Parameters

<<GENERATE:PARAMS:export>>

### /export [GET]

+ Request Plain Text Export

    + Headers
    
            Accept: text/plain
            
+ Response 200 (text/plain)
    
    + Body
    
            Hash,BlockNumber,TransactionIndex,Timestamp,Date,From,FromName,To,ToName,EtherValue,DollarsThen,EtherGasCost,GasCostThen,GasUsed,isError,inFlow,outFlow,Internal,Encoding,FunctionName,Category,Note
            "0xced11523d71c444ce6d4296aaf4be2198d13358dd33925218ba5e49ccee5de43","7218566","6","1550131308","2/14/2019 8:01:48","0x512e07a093aaa20ba288392eadf03838c7a4e522",,"0x0",,"0","0","0.113701400000000000","13.871571937014","5685070","0","","","0","0x60806040",,"contract creation",

+ Request JSON Export

    + Headers
    
            Accept: application/json
            
+ Response 200 (application/json)

    + Body
    
            {
              "status": "ok",
              "data": [
                {
                  "hash": "0x184ff1f00c1c5da9c62774e4e2bf0925de39046e056c13edf31f0bb9ce4d9b38",
                  "blockHash": "0xda4c0d8c4df359aeb0dbcdc98767da4f31f95c3a9eb705a96933bd5322c8007f",
                  "blockNumber": 89796,
                  "transactionIndex": 6,
                  "timestamp": 1439629343,
                  "from": "0xe6a7a1d47ff21b6321162aea7c6cb457d5476bca",
                  "to": "0x3b01ebd2419f6d39db6ab4471e6382848716641f",
                  "value": 83372067757175030000,
                  "gas": 22000,
                  "gasPrice": 55815739021,
                  "isError": 0,
                  "receipt": {
                    "contractAddress": "0x0",
                    "gasUsed": 21000,
                    "logs": [],
                    "status": null
                  },
                  "traces": [],
                  "gasCost": 1172130519441000,
                  "gasUsed": 21000,
                  "date": "2015-08-15 09:02:23 UTC",
                  "datesh": "2015-08-15",
                  "time": "9:02:23 UTC",
                  "age": "21450442",
                  "ether": 83.372067757175030000
                }
              ]
            }

## Slurp [<<GENERATE:URI:slurp>>]

Slurp against etherscan.

+ Parameters

<<GENERATE:PARAMS:slurp>>

### /slurp [GET]

+ Request JSON data
    
    + Headers
    
            Accept: application/json
            
+ Response 200 (application/json)

    + Body
    
            [
                {
                    "gasLimit": 3141592,
                    "gasUsed": 0,
                    "hash": "0x3e5c2f13bc01a0a32c7eda3560ec3ede19c9d2f6c0fda8436999eee2914e862d",
                    "blockNumber": 101010,
                    "parentHash": "0x8290679004240a002dcf274bf56310c2654b5137c643e5c20ff647ebda61033b",
                    "miner": "0xc603ab5ef41fc61aa8b76beddb09e3cfcbb174bd",
                    "difficulty": 3871451743585,
                    "price": 0,
                    "finalized": 1,
                    "timestamp": 1439815989,
                    "transactions": [],
                    "date": "2015-08-17 12:53:09 UTC",
                    "age": "21263796"
                }
            ]

## names [<<GENERATE:URI:names>>]

I don't really know what this is.

+ Parameters

<<GENERATE:PARAMS:names>>

### /names [GET]

+ Request JSON data

    + Headers
            
            Accept: application/json
            
+ Response 200 (application/json)

    + Body
    
             { "type": "CEthState", "data": [
                  {
                    "schema": 5005,
                    "deleted": 0,
                    "showing": 1,
                    "cname": "EthState",
                    "blockNumber": 1365929,
                    "balance": 0,
                    "nonce": 0,
                    "code": "0x",
                    "storage": "",
                    "address": "0x06012c8cf97bead5deae237070f9587f8e7a266d",
                    "deployed": 0,
                    "accttype": "EOA",
                    "ether": 0.000000000000000000
                  }
                ], "meta": {"pending": 622000,"staging": 622000,"finalized": 539800,"client": 1365929 } }


## ABI [<<GENERATE:URI:abi>>]

Get abi.

+ Parameters

<<GENERATE:PARAMS:abi>>

### /abi [GET]

+ Request JSON data
    
    + Headers
    
            Accept: application/json
            
+ Response 200 (application/json)

    + Body
    
            [
                {
                    "gasLimit": 3141592,
                    "gasUsed": 0,
                    "hash": "0x3e5c2f13bc01a0a32c7eda3560ec3ede19c9d2f6c0fda8436999eee2914e862d",
                    "blockNumber": 101010,
                    "parentHash": "0x8290679004240a002dcf274bf56310c2654b5137c643e5c20ff647ebda61033b",
                    "miner": "0xc603ab5ef41fc61aa8b76beddb09e3cfcbb174bd",
                    "difficulty": 3871451743585,
                    "price": 0,
                    "finalized": 1,
                    "timestamp": 1439815989,
                    "transactions": [],
                    "date": "2015-08-17 12:53:09 UTC",
                    "age": "21263796"
                }
            ]

# Group State

## View State detail [<<GENERATE:URI:state>>]

Look at state.

+ Parameters

<<GENERATE:PARAMS:state>>

### /state [GET]

+ Request JSON data
    
    + Headers
    
            Accept: application/json
            
+ Response 200 (application/json)

    + Body
    
            [
                {
                    "gasLimit": 3141592,
                    "gasUsed": 0,
                    "hash": "0x3e5c2f13bc01a0a32c7eda3560ec3ede19c9d2f6c0fda8436999eee2914e862d",
                    "blockNumber": 101010,
                    "parentHash": "0x8290679004240a002dcf274bf56310c2654b5137c643e5c20ff647ebda61033b",
                    "miner": "0xc603ab5ef41fc61aa8b76beddb09e3cfcbb174bd",
                    "difficulty": 3871451743585,
                    "price": 0,
                    "finalized": 1,
                    "timestamp": 1439815989,
                    "transactions": [],
                    "date": "2015-08-17 12:53:09 UTC",
                    "age": "21263796"
                }
            ]

# Group Data

## View block detail [<<GENERATE:URI:blocks>>]

Look at a block.

+ Parameters

<<GENERATE:PARAMS:blocks>>

### /blocks [GET]

+ Request JSON data
    
    + Headers
    
            Accept: application/json
            
+ Response 200 (application/json)

    + Body
    
            [
                {
                    "gasLimit": 3141592,
                    "gasUsed": 0,
                    "hash": "0x3e5c2f13bc01a0a32c7eda3560ec3ede19c9d2f6c0fda8436999eee2914e862d",
                    "blockNumber": 101010,
                    "parentHash": "0x8290679004240a002dcf274bf56310c2654b5137c643e5c20ff647ebda61033b",
                    "miner": "0xc603ab5ef41fc61aa8b76beddb09e3cfcbb174bd",
                    "difficulty": 3871451743585,
                    "price": 0,
                    "finalized": 1,
                    "timestamp": 1439815989,
                    "transactions": [],
                    "date": "2015-08-17 12:53:09 UTC",
                    "age": "21263796"
                }
            ]

## View transactions detail [<<GENERATE:URI:transactions>>]

Look at transactions.

+ Parameters

<<GENERATE:PARAMS:transactions>>

### /transactions [GET]

+ Request JSON data
    
    + Headers
    
            Accept: application/json
            
+ Response 200 (application/json)

    + Body
    
            [
                {
                    "gasLimit": 3141592,
                    "gasUsed": 0,
                    "hash": "0x3e5c2f13bc01a0a32c7eda3560ec3ede19c9d2f6c0fda8436999eee2914e862d",
                    "blockNumber": 101010,
                    "parentHash": "0x8290679004240a002dcf274bf56310c2654b5137c643e5c20ff647ebda61033b",
                    "miner": "0xc603ab5ef41fc61aa8b76beddb09e3cfcbb174bd",
                    "difficulty": 3871451743585,
                    "price": 0,
                    "finalized": 1,
                    "timestamp": 1439815989,
                    "transactions": [],
                    "date": "2015-08-17 12:53:09 UTC",
                    "age": "21263796"
                }
            ]

## View receipts detail [<<GENERATE:URI:receipts>>]

Look at receipts.

+ Parameters

<<GENERATE:PARAMS:receipts>>

### /receipts [GET]

+ Request JSON data
    
    + Headers
    
            Accept: application/json
            
+ Response 200 (application/json)

    + Body
    
            [
                {
                    "gasLimit": 3141592,
                    "gasUsed": 0,
                    "hash": "0x3e5c2f13bc01a0a32c7eda3560ec3ede19c9d2f6c0fda8436999eee2914e862d",
                    "blockNumber": 101010,
                    "parentHash": "0x8290679004240a002dcf274bf56310c2654b5137c643e5c20ff647ebda61033b",
                    "miner": "0xc603ab5ef41fc61aa8b76beddb09e3cfcbb174bd",
                    "difficulty": 3871451743585,
                    "price": 0,
                    "finalized": 1,
                    "timestamp": 1439815989,
                    "transactions": [],
                    "date": "2015-08-17 12:53:09 UTC",
                    "age": "21263796"
                }
            ]

## View logs detail [<<GENERATE:URI:logs>>]

Look at logs.

+ Parameters

<<GENERATE:PARAMS:logs>>

### /logs [GET]

+ Request JSON data
    
    + Headers
    
            Accept: application/json
            
+ Response 200 (application/json)

    + Body
    
            [
                {
                    "gasLimit": 3141592,
                    "gasUsed": 0,
                    "hash": "0x3e5c2f13bc01a0a32c7eda3560ec3ede19c9d2f6c0fda8436999eee2914e862d",
                    "blockNumber": 101010,
                    "parentHash": "0x8290679004240a002dcf274bf56310c2654b5137c643e5c20ff647ebda61033b",
                    "miner": "0xc603ab5ef41fc61aa8b76beddb09e3cfcbb174bd",
                    "difficulty": 3871451743585,
                    "price": 0,
                    "finalized": 1,
                    "timestamp": 1439815989,
                    "transactions": [],
                    "date": "2015-08-17 12:53:09 UTC",
                    "age": "21263796"
                }
            ]

## View traces detail [<<GENERATE:URI:traces>>]

Look at traces.

+ Parameters

<<GENERATE:PARAMS:traces>>

### /traces [GET]

+ Request JSON data
    
    + Headers
    
            Accept: application/json
            
+ Response 200 (application/json)

    + Body
    
            [
                {
                    "gasLimit": 3141592,
                    "gasUsed": 0,
                    "hash": "0x3e5c2f13bc01a0a32c7eda3560ec3ede19c9d2f6c0fda8436999eee2914e862d",
                    "blockNumber": 101010,
                    "parentHash": "0x8290679004240a002dcf274bf56310c2654b5137c643e5c20ff647ebda61033b",
                    "miner": "0xc603ab5ef41fc61aa8b76beddb09e3cfcbb174bd",
                    "difficulty": 3871451743585,
                    "price": 0,
                    "finalized": 1,
                    "timestamp": 1439815989,
                    "transactions": [],
                    "date": "2015-08-17 12:53:09 UTC",
                    "age": "21263796"
                }
            ]

# Group Other

## View quotes detail [<<GENERATE:URI:quotes>>]

Look at quotes.

+ Parameters

<<GENERATE:PARAMS:quotes>>

### /quotes [GET]

+ Request JSON data
    
    + Headers
    
            Accept: application/json
            
+ Response 200 (application/json)

    + Body
    
            [
                {
                    "gasLimit": 3141592,
                    "gasUsed": 0,
                    "hash": "0x3e5c2f13bc01a0a32c7eda3560ec3ede19c9d2f6c0fda8436999eee2914e862d",
                    "blockNumber": 101010,
                    "parentHash": "0x8290679004240a002dcf274bf56310c2654b5137c643e5c20ff647ebda61033b",
                    "miner": "0xc603ab5ef41fc61aa8b76beddb09e3cfcbb174bd",
                    "difficulty": 3871451743585,
                    "price": 0,
                    "finalized": 1,
                    "timestamp": 1439815989,
                    "transactions": [],
                    "date": "2015-08-17 12:53:09 UTC",
                    "age": "21263796"
                }
            ]

# Group Admin

## View status detail [<<GENERATE:URI:status>>]

Look at status. Great status.

+ Parameters

<<GENERATE:PARAMS:status>>

### /status [GET]

+ Request JSON data
    
    + Headers
    
            Accept: application/json
            
+ Response 200 (application/json)

    + Body
    
            [
                {
                    "gasLimit": 3141592,
                    "gasUsed": 0,
                    "hash": "0x3e5c2f13bc01a0a32c7eda3560ec3ede19c9d2f6c0fda8436999eee2914e862d",
                    "blockNumber": 101010,
                    "parentHash": "0x8290679004240a002dcf274bf56310c2654b5137c643e5c20ff647ebda61033b",
                    "miner": "0xc603ab5ef41fc61aa8b76beddb09e3cfcbb174bd",
                    "difficulty": 3871451743585,
                    "price": 0,
                    "finalized": 1,
                    "timestamp": 1439815989,
                    "transactions": [],
                    "date": "2015-08-17 12:53:09 UTC",
                    "age": "21263796"
                }
            ]
